### ISSUE TITLE
Record List does not display in Email

### ISSUE THREAD

**Issue by sanjacornelius** [ProcessMaker/connector-send-email#72]

**Comment by nolanpro** [comment]
This is going to require the long-put-off update to the dependent version of screen builder. It's currently using 0.17.77 and we have been holding off on the updating since there are a number of browser dependent things that have creeped into screen builder since we last had to deal with this (html editor). I'm going to dive into this trench and see if I get it all working with the latest version of and will probably require substantial changes to screen builder.
